# Generated by Django 4.2.1 on 2023-06-27 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

from rpg.models.base import BaseModel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp_growth', BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('mp_growth', BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('str_growth', BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('int_growth', BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('dex_growth', BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_hp', models.PositiveSmallIntegerField(default=1)),
                ('base_mp', models.PositiveSmallIntegerField(default=1)),
                ('base_str', models.PositiveSmallIntegerField(default=1)),
                ('base_int', models.PositiveSmallIntegerField(default=1)),
                ('base_dex', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_required', models.PositiveSmallIntegerField(default=1)),
                ('damage', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=1)),
                ('modifier', BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('damage', 'Damage'), ('heal', 'Heal'), ('buff', 'Buff'), ('debuff', 'Debuff')], default='damage', max_length=6)),
                ('duration', models.PositiveSmallIntegerField(default=1)),
                ('attribute', models.CharField(choices=[('str', 'Str'), ('dex', 'Dex'), ('int', 'Int')], default='str', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side_effect_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpg.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1)),
                ('mp', models.IntegerField(default=1)),
                ('str', models.IntegerField(default=1)),
                ('dex', models.IntegerField(default=1)),
                ('int', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Neutral'), (2, 'Dead'), (3, 'Undead'), (4, 'Poisoned'), (5, 'Frozen'), (6, 'Shoked'), (7, 'Casting'), (8, 'Resting'), (9, 'Enraged'), (10, 'Stunned'), (11, 'Regenerating')], default=1)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('faction', models.IntegerField(choices=[(1, 'Ally'), (2, 'Enemy'), (3, 'Neutral')], default=3)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.job')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.job')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='races',
            field=models.ManyToManyField(related_name='races', through='rpg.JobRace', to='rpg.race'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='rpg.skill'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1)),
                ('mp', models.IntegerField(default=1)),
                ('str', models.IntegerField(default=1)),
                ('dex', models.IntegerField(default=1)),
                ('int', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Neutral'), (2, 'Dead'), (3, 'Undead'), (4, 'Poisoned'), (5, 'Frozen'), (6, 'Shoked'), (7, 'Casting'), (8, 'Resting'), (9, 'Enraged'), (10, 'Stunned'), (11, 'Regenerating')], default=1)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('exp', models.PositiveSmallIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.job')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.race')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
