# Generated by Django 4.2.1 on 2023-06-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp_growth', models.IntegerField(default=1)),
                ('mp_growth', models.IntegerField(default=1)),
                ('str_growth', models.IntegerField(default=1)),
                ('int_growth', models.IntegerField(default=1)),
                ('dex_growth', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_required', models.IntegerField(default=1)),
                ('damage', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=1)),
                ('modifier', models.IntegerField(default=1)),
                ('attribute', models.CharField(choices=[('str', 'Str'), ('dex', 'Dex'), ('int', 'Int')], default='str', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.job')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1)),
                ('mp', models.IntegerField(default=1)),
                ('str', models.IntegerField(default=1)),
                ('dex', models.IntegerField(default=1)),
                ('int', models.IntegerField(default=1)),
                ('faction', models.IntegerField(choices=[(1, 'Ally'), (2, 'Enemy'), (3, 'Neutral')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.job')),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.race')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='races',
            field=models.ManyToManyField(to='rpg.race'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='rpg.skill'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField()),
                ('hp', models.IntegerField(default=1)),
                ('mp', models.IntegerField(default=1)),
                ('str', models.IntegerField(default=1)),
                ('dex', models.IntegerField(default=1)),
                ('int', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Alive'), (2, 'Dead'), (3, 'Undead')], default=1)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.job')),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.race')),
            ],
        ),
    ]
