# Generated by Django 4.2.1 on 2023-06-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AlterField(
            model_name='job',
            name='races',
            field=models.ManyToManyField(through='rpg.JobRace', to='rpg.race'),
        ),
    ]
