# Generated by Django 4.2.1 on 2023-06-09 07:47

import django.core.validators
from django.db import migrations, models
import rpg.validations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_alter_character_exp_alter_character_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='base_dex',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='race',
            name='base_hp',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='race',
            name='base_int',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='race',
            name='base_mp',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='race',
            name='base_str',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='race',
            name='dex_growth',
            field=rpg.validations.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='hp_growth',
            field=rpg.validations.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='int_growth',
            field=rpg.validations.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='mp_growth',
            field=rpg.validations.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='str_growth',
            field=rpg.validations.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
