# Generated by Django 4.2.1 on 2023-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_race_base_dex_race_base_hp_race_base_int_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='status',
            field=models.IntegerField(choices=[(1, 'Neutral'), (2, 'Dead'), (3, 'Undead'), (4, 'Poisoned'), (5, 'Frozen'), (6, 'Shoked'), (7, 'Casting'), (8, 'Resting'), (9, 'Enraged'), (10, 'Stunned'), (11, 'Regenerating')], default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.IntegerField(choices=[(1, 'Neutral'), (2, 'Dead'), (3, 'Undead'), (4, 'Poisoned'), (5, 'Frozen'), (6, 'Shoked'), (7, 'Casting'), (8, 'Resting'), (9, 'Enraged'), (10, 'Stunned'), (11, 'Regenerating')], default=1),
        ),
    ]
