# Generated by Django 4.2.1 on 2023-06-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_npc_status_alter_character_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='race_id',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='race_id',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='side_effect_skill_id',
            new_name='side_effect_skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job_id',
        ),
    ]
