# Generated by Django 4.2.1 on 2023-06-10 09:52

import django.core.validators
from django.db import migrations
from rpg.models.base import BaseModel


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_rename_job_id_character_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='dex_growth',
            field=BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='hp_growth',
            field=BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='int_growth',
            field=BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='mp_growth',
            field=BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='str_growth',
            field=BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='modifier',
            field=BaseModel.PositiveDecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
