# Generated by Django 4.2.1 on 2023-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0007_alter_race_dex_growth_alter_race_hp_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
