# Generated by Django 4.2.1 on 2023-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0008_race_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
